SERIAL_WRITE = "SERIAL_WRITE"
SERIAL_READ = "SERIAL_READ"

SERIAL_DRAW = "SERIAL_DRAW"

SERIAL_TEST = "test_serial"
CHECK_DISTANCE = "measure_dist"

ACTION_EXECUTE = "ACTION:EXECUTE"
ACTION_MOVEMENT = "ACTION:MOVEMENT"

SHUTDOWN = "SHUTDOWN"
REBOOT = "REBOOT"
LED_ON = "LED_ON"
LED_OFF = "LED_OFF"
LED_FLASH = "LED_TOGGLE"

LISTEN_STT = "LISTEN_STT"

TERMINATE = "TERMINATE"
PATROL = "PATROL"
TALK = "TALK"

TALK_SYSTEMS = "TALK_SYSTEMS"

HUMAN = "HUMAN"
OBJECT = "OBJECT"

PRI_MSN_STAND_ORD = "PRI_MSN:STAND_ORD"
SEC_MSN_STAND_ORD = "SEC_MSN:STAND_ORD"
TER_MSN_STAND_ORD = "TER_MSN:STAND_ORD"

HARDWARE_PI = "HARDWARE_PI"

ANY = [SERIAL_WRITE, SERIAL_READ, SERIAL_DRAW, ACTION_EXECUTE, ACTION_MOVEMENT, SHUTDOWN, REBOOT, LED_ON, LED_OFF,
       LED_FLASH, LISTEN_STT, TERMINATE, PATROL, PRI_MSN_STAND_ORD, SEC_MSN_STAND_ORD, TER_MSN_STAND_ORD, HARDWARE_PI,
       CHECK_DISTANCE, SERIAL_TEST, HUMAN, OBJECT, TALK_SYSTEMS]
