SERIAL_WRITE = "SERIAL_WRITE"
SERIAL_READ = "SERIAL_READ"

SERIAL_DRAW = "SERIAL_DRAW"

ACTION_EXECUTE = "ACTION:EXECUTE"
ACTION_MOVEMENT = "ACTION:MOVEMENT"

SHUTDOWN = "SHUTDOWN"
REBOOT = "REBOOT"
LED_ON = "LED_ON"
LED_OFF = "LED_OFF"
LED_FLASH = "LED_TOGGLE"

LISTEN_STT = "LISTEN_STT"

ANY = [SERIAL_WRITE, SERIAL_READ, SERIAL_DRAW, ACTION_EXECUTE, ACTION_MOVEMENT, SHUTDOWN, REBOOT, LED_ON, LED_OFF,
       LED_FLASH, LISTEN_STT]
